### ISSUE TITLE
Is it possible to disable an item?

### ISSUE THREAD

**Issue by fprosper** [jinthagerman/JBTabBarController#3]
Hi I am using the code heavily and I need a way to disable some items at runtime, did you think about it, is there a way? Thanks.

**Comment by jinthagerman** [comment]
Do you mean disable the button (ignore touch events) or remove the item visually (animated?)?

Both are doable, but simply disabling a button is much easier. Tell me which you need and I should be able to help you out.

I was planning to implement the [UITabBarControllerDelegate methods](http://developer.apple.com/library/ios/#DOCUMENTATION/UIKit/Reference/UITabBarControllerDelegate_Protocol/Reference/Reference.html) at some point. The "Managing Tab Bar Selections" are more of a priority to me, but at some point I hope to implement the rest.

However, I think what is more urgent than that is implementing some KVO on the items so that the tabbar is more dynamic.

**Comment by fprosper** [comment]
Hi Jin,

I was thinking the implementation of two properties: 

isDisabled -> the button is there but ignores touch events
disabledImage -> the image to display when the button is disabled

I can help giving a look to that even if I was hoping they were already there as the project I am working on right now is taking up all of my time. Please let me know if/when you plan to implement something like that.

Many thanks,
F.

## 

Fabrizio Prosperi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jinthagerman** [comment]
`disabledImage` is not something I would implement as it is not a behaviour UITabBarController implements.

Functionality like the `isDisabled` property you described will be handled using the UITabBarControllerDelegate protocol (when I have time to implement that) using `– tabBarController:shouldSelectViewController:`.

However, what you have describe should be relatively simple to implement. Check out the Gist below for some hints.

https://gist.github.com/90339cb6b1a477bdee98

**Comment by fprosper** [comment]
Thank you Jin, the gist gave me good hints to implement 'disabled' in a way good enough for my project.  

Cheers,
F.

## 

Fabrizio Prosperi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jinthagerman** [comment]
I've added the needed UITabBarControllerDelegate methods to do this the UIKit way in v0.4.

**Comment by fprosper** [comment]
Thank you Jin, I look forward implementing it then. Cheers.
